# Generated by Django 4.1.3 on 2023-03-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="contact",
            new_name="contact_complaint",
        ),
    ]
