# Generated by Django 4.1.7 on 2023-03-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_rename_contact_contact_complaint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact_complaint",
            name="email",
            field=models.CharField(max_length=40),
        ),
    ]
