# Generated by Django 4.1.7 on 2023-03-21 07:27

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_img", models.ImageField(upload_to="blog_img")),
                ("person_name", models.CharField(max_length=20)),
                ("date", models.DateField(auto_now_add=True)),
                ("food", models.CharField(max_length=20)),
                ("blog_title", tinymce.models.HTMLField()),
                ("detail", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_body", models.TextField()),
                ("name", models.CharField(max_length=200)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.blogs"
                    ),
                ),
            ],
        ),
    ]
