# Generated by Django 4.1.7 on 2023-03-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogs",
            name="detail",
        ),
        migrations.AlterField(
            model_name="blogs",
            name="blog_title",
            field=models.TextField(),
        ),
    ]
