# Generated by Django 4.1.7 on 2023-03-21 08:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_blogs_detail_alter_blogs_blog_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="detail",
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="blog_title",
            field=models.TextField(null=True),
        ),
    ]
