# Generated by Django 4.1.3 on 2023-03-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="happy_customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comments", models.CharField(max_length=500)),
                ("person_img", models.ImageField(upload_to="home_customers_img")),
                ("person_name", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="home_menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dis_img", models.ImageField(upload_to="home_menu_img")),
                ("dis_name", models.CharField(max_length=50)),
                ("dis_detail", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="home_news_blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_img", models.ImageField(upload_to="home_blog_img")),
                ("person_name", models.CharField(max_length=20)),
                ("date", models.DateField(auto_now_add=True)),
                ("food", models.CharField(max_length=20)),
                ("heading", models.CharField(max_length=50)),
                ("detail", models.CharField(max_length=500)),
            ],
        ),
    ]
