# Generated by Django 4.1.3 on 2023-03-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="happy_customers",
            name="half_img",
            field=models.ImageField(default=1.0, upload_to="home_customers_img"),
            preserve_default=False,
        ),
    ]
