# Generated by Django 4.1.7 on 2023-03-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="burgur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dis_name", models.CharField(max_length=30)),
                ("detail", models.CharField(max_length=50)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="desserts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dis_name", models.CharField(max_length=30)),
                ("detail", models.CharField(max_length=50)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="pasta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dis_name", models.CharField(max_length=30)),
                ("detail", models.CharField(max_length=50)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dis_name", models.CharField(max_length=30)),
                ("detail", models.CharField(max_length=50)),
                ("price", models.FloatField()),
            ],
        ),
    ]
