# Generated by Django 4.1.7 on 2023-03-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="breakfast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dis_name", models.CharField(max_length=30)),
                ("dis_img", models.ImageField(upload_to="Main_course_menu")),
                ("detail", models.CharField(max_length=50)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="dinner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dis_name", models.CharField(max_length=30)),
                ("dis_img", models.ImageField(upload_to="Main_course_menu")),
                ("detail", models.CharField(max_length=50)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="healty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dis_name", models.CharField(max_length=30)),
                ("dis_img", models.ImageField(upload_to="Main_course_menu")),
                ("detail", models.CharField(max_length=50)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="lunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dis_name", models.CharField(max_length=30)),
                ("dis_img", models.ImageField(upload_to="Main_course_menu")),
                ("detail", models.CharField(max_length=50)),
                ("price", models.FloatField()),
            ],
        ),
    ]
